/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.websites.dashboard.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WebSitesDashboard service. Represents a row in the &quot;websitesdashboard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.websites.dashboard.model.impl.WebSitesDashboardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.websites.dashboard.model.impl.WebSitesDashboardImpl}.
 * </p>
 *
 * @author liferay
 * @see WebSitesDashboard
 * @see com.websites.dashboard.model.impl.WebSitesDashboardImpl
 * @see com.websites.dashboard.model.impl.WebSitesDashboardModelImpl
 * @generated
 */
public interface WebSitesDashboardModel extends BaseModel<WebSitesDashboard> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a web sites dashboard model instance should use the {@link WebSitesDashboard} interface instead.
	 */

	/**
	 * Returns the primary key of this web sites dashboard.
	 *
	 * @return the primary key of this web sites dashboard
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this web sites dashboard.
	 *
	 * @param primaryKey the primary key of this web sites dashboard
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the web ID of this web sites dashboard.
	 *
	 * @return the web ID of this web sites dashboard
	 */
	public long getWebId();

	/**
	 * Sets the web ID of this web sites dashboard.
	 *
	 * @param webId the web ID of this web sites dashboard
	 */
	public void setWebId(long webId);

	/**
	 * Returns the group ID of this web sites dashboard.
	 *
	 * @return the group ID of this web sites dashboard
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this web sites dashboard.
	 *
	 * @param groupId the group ID of this web sites dashboard
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this web sites dashboard.
	 *
	 * @return the company ID of this web sites dashboard
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this web sites dashboard.
	 *
	 * @param companyId the company ID of this web sites dashboard
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this web sites dashboard.
	 *
	 * @return the user ID of this web sites dashboard
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this web sites dashboard.
	 *
	 * @param userId the user ID of this web sites dashboard
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this web sites dashboard.
	 *
	 * @return the user uuid of this web sites dashboard
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this web sites dashboard.
	 *
	 * @param userUuid the user uuid of this web sites dashboard
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this web sites dashboard.
	 *
	 * @return the user name of this web sites dashboard
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this web sites dashboard.
	 *
	 * @param userName the user name of this web sites dashboard
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this web sites dashboard.
	 *
	 * @return the create date of this web sites dashboard
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this web sites dashboard.
	 *
	 * @param createDate the create date of this web sites dashboard
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the expire date of this web sites dashboard.
	 *
	 * @return the expire date of this web sites dashboard
	 */
	public Date getExpireDate();

	/**
	 * Sets the expire date of this web sites dashboard.
	 *
	 * @param expireDate the expire date of this web sites dashboard
	 */
	public void setExpireDate(Date expireDate);

	/**
	 * Returns the renew date of this web sites dashboard.
	 *
	 * @return the renew date of this web sites dashboard
	 */
	public Date getRenewDate();

	/**
	 * Sets the renew date of this web sites dashboard.
	 *
	 * @param renewDate the renew date of this web sites dashboard
	 */
	public void setRenewDate(Date renewDate);

	/**
	 * Returns the price of this web sites dashboard.
	 *
	 * @return the price of this web sites dashboard
	 */
	public double getPrice();

	/**
	 * Sets the price of this web sites dashboard.
	 *
	 * @param price the price of this web sites dashboard
	 */
	public void setPrice(double price);

	/**
	 * Returns the active of this web sites dashboard.
	 *
	 * @return the active of this web sites dashboard
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this web sites dashboard is active.
	 *
	 * @return <code>true</code> if this web sites dashboard is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this web sites dashboard is active.
	 *
	 * @param active the active of this web sites dashboard
	 */
	public void setActive(boolean active);

	/**
	 * Returns the transition ID of this web sites dashboard.
	 *
	 * @return the transition ID of this web sites dashboard
	 */
	@AutoEscape
	public String getTransitionId();

	/**
	 * Sets the transition ID of this web sites dashboard.
	 *
	 * @param transitionId the transition ID of this web sites dashboard
	 */
	public void setTransitionId(String transitionId);

	/**
	 * Returns the status of this web sites dashboard.
	 *
	 * @return the status of this web sites dashboard
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this web sites dashboard.
	 *
	 * @param status the status of this web sites dashboard
	 */
	public void setStatus(String status);

	/**
	 * Returns the comments of this web sites dashboard.
	 *
	 * @return the comments of this web sites dashboard
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this web sites dashboard.
	 *
	 * @param comments the comments of this web sites dashboard
	 */
	public void setComments(String comments);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WebSitesDashboard webSitesDashboard);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WebSitesDashboard> toCacheModel();

	@Override
	public WebSitesDashboard toEscapedModel();

	@Override
	public WebSitesDashboard toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}